apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yffc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-yffc@sha256:8d4f7c7104816e62b51ee9ed79df1e8b9b27a2c69961eac6904b1cb4c56ae43b
        name: my-nodejs
        resources: {}
status: {}
